eshop/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eshop.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Cart()
        {
            return View();
        }

        public ActionResult Checkout()
        {
            return View();
        }
    }
}

eshop/Views/Cart/Cart.cshtml
<section>
    <img class="img-fluid mb-5" src="~/images/debra/debra (1).png" />
    <div class="banner-text text-center">
        <h2>Your Shopping Cart</h2>
        <p>Home > <span>Your Shopping Cart</span></p>
    </div>
</section>
<div class="container mb-5">
    <table class="shadow table table-bordered text-center align-items-center mb-3">
        <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Product</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
                <th scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="align-middle">
                    <img src="~/images/debra/debra (16).jpg" height="150" />
                </td>
                <td class="align-middle">11. Product with video navy</td>
                <td class="align-middle px-5">$35.00</td>
                <td class="align-middle px-5">
                    <form >
                        <input class="itemCount" type="number" value="1" min="0" max="100" step="1" required/>
                    </form>
                </td>
                <td class="align-middle px-5">$35.00</td>
                <td class="align-middle px-5">
                    <a href="">
                        <i class="fa fa-times"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <td class="align-middle">
                    <img src="~/images/debra/debra (16).jpg" height="150" />
                </td>
                <td class="align-middle">11. Product with video navy</td>
                <td class="align-middle px-5">$35.00</td>
                <td class="align-middle px-5">
                    <form >
                        <input class="itemCount" type="number" value="1" min="0" max="100" step="1" required/>
                    </form>
                </td>
                <td class="align-middle px-5">$35.00</td>
                <td class="align-middle px-5">
                    <a href="">
                        <i class="fa fa-times"></i>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="row justify-content-end mb-5">
        <div class="col-auto">
            <button class="btn btn-dark">
                Update cart
            </button>
            <button class="btn btn-dark">
                Continue Shopping
            </button>
            <button class="btn btn-dark">
                Clear Cart
            </button>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-6">
            <h4>Get Shipping estimatess</h4>
            <form>
                <div class="form-row">
                    <div class="col-7">
                        <div class="form-group">
                            <select class="form-control" id="stateSelect">
                                <option>----</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <input type="text" class="form-control" id="zipInput" placeholder="Zip/Postal Code" required>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-dark">Calculate shipping</button>
            </form>
        </div>
        <div class="col-6">
            <h4>Cart Totals</h4>
            <div class="row text-left mb-3 m-1">
                <div class="col-6 border">
                    <div class="p-2">
                        <b>Subtotal</b>
                    </div>
                </div>
                <div class="col-6 border">
                    <div class="p-2">
                        $70.00
                    </div>
                </div>
                <div class="col-6 border">
                    <div class="p-2">
                        <b>Total</b>
                    </div>
                </div>
                <div class="col-6 border">
                    <div class="p-2">
                        <b>$70.00</b>
                    </div>
                </div>
            </div>
            <form class="p-0">
                @Html.ActionLink("Proceed to Checkout", "Checkout", "Cart", new { area = "" }, new { @class = "btn btn-dark" })
            </form>
        </div>
    </div>
</div>
<script src="./src/bootstrap-input-spinner.js"></script>
<script>
    $("input[type='number']").inputSpinner();
</script>

eshop/Views/Cart/Checkout.cshtml
<section>
    <div class="container my-5">
        <div class="row">
            <div class="col-7 border-right">
                <div class="mb-2 debra-title">
                    DEBRA
                </div>
                <p><span>Cart</span> > Information > Shipping > Payment</p>
                <form class="my-4">
                    <div class="row my-3">
                        <div class="col-6 justify-content-start">
                            <h5>Contact information</h5>
                        </div>
                        <div class="col-6 justify-content-end">
                            Already have and account? <a href="">Log in</a>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="inputAddress" placeholder="Email or mobile phone number">
                    </div>
                    <div class="form-group mb-5">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="newsletter">
                            <label class="form-check-label" for="newsletter">
                                Keep me up to date on news and exclusive offers
                            </label>
                        </div>
                    </div>
                    <div class="row my-3">
                        <div class="col-6 justify-content-start">
                            <h5>Shipping address</h5>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control" id="inputEmail4" placeholder="First name (optional)">
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control" id="inputPassword4" placeholder="Last name" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="inputAddress" placeholder="Address" required>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="inputAparment" placeholder="Apartment, suite, etc. (optional))">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="inputCity" placeholder="City">
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <select id="inputState" class="form-control">
                                <option selected>Choose...</option>
                                <option>...</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control" id="inputZip" placeholder="Postal code">
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="gridCheck">
                            <label class="form-check-label" for="gridCheck">
                                Save this information for next time
                            </label>
                        </div>
                    </div>
                    <div class="row my-3 align-content-center">
                        <div class="col-6 justify-content-start align-self-center">
                            <a href="" class="active-pink">< Return to cart</a>
                        </div>
                        <div class="col-6 justify-content-end text-right align-self-center">
                            <button type="submit" class="btn pink-button">Continue to shipping</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-5 contact">
                <div class="px-3 py-4">
                    <div class="col p-0 mb-2">
                        <div class="row">
                            <div class="col-3">
                                <img src="~/images/debra/debra (11).jpg" class="rounded img-fluid border" alt="...">
                            </div>
                            <div class="col-9  align-self-center">
                                <div class="row align-self-center ">
                                    <div class="col-9 align-self-start">
                                        <span>11. Product with video</span>
                                    </div>
                                    <div class="col-3 align-self-end text-right">
                                        <span>$39.90</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col p-0 mb-2">
                        <div class="row">
                            <div class="col-3">
                                <img src="~/images/debra/debra (11).jpg" class="rounded img-fluid border" alt="...">
                            </div>
                            <div class="col-9  align-self-center">
                                <div class="row align-self-center ">
                                    <div class="col-9 align-self-start">
                                        <span>11. Product with video</span>
                                    </div>
                                    <div class="col-3 align-self-end text-right">
                                        <span>$39.90</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col p-0 mb-2">
                        <div class="row">
                            <div class="col-3">
                                <img src="~/images/debra/debra (11).jpg" class="rounded img-fluid border" alt="...">
                            </div>
                            <div class="col-9  align-self-center">
                                <div class="row align-self-center ">
                                    <div class="col-9 align-self-start">
                                        <span>11. Product with video</span>
                                    </div>
                                    <div class="col-3 align-self-end text-right">
                                        <span>$39.90</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
                <hr />
                <div class="row mb-2">
                    <div class="col-6">
                        Subtotal
                    </div>
                    <div class="col-6 text-right">
                        $89.00
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-6">
                        Shipping
                    </div>
                    <div class="col-6 text-right">
                        Calculated at next step
                    </div>
                </div>
                <hr />
                <div class="row my-2">
                    <div class="col-6">
                        Total
                    </div>
                    <div class="col-6 text-right">
                        usd $89.00
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>